"""Enterprise Security and Device Tracking

Revision ID: 994f8199e8c5
Revises: a1e9d8c5f59c
Create Date: 2026-07-23 16:30:09.379085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Enterprise Security and Device Tracking

Revision ID: 994f8199e8c5
Revises: a1e9d8c5f59c
Create Date: 2026-07-23 16:30:09.379085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994f8199e8c5'
down_revision: Union[str, Sequence[str], None] = 'a1e9d8c5f59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'FINANCE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_device_id'), 'refresh_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_device_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_column('refresh_tokens', 'last_activity')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'platform')
    op.drop_column('refresh_tokens', 'browser')
    op.drop_column('refresh_tokens', 'device_id')
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
