"""Flight Intelligence and Airport Ops

Revision ID: a1e9d8c5f59c
Revises: 32800fa08cf6
Create Date: 2026-07-23 16:23:42.652267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e9d8c5f59c'
down_revision: Union[str, Sequence[str], None] = '32800fa08cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_status_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('airline_code', sa.String(), nullable=True),
    sa.Column('origin_code', sa.String(), nullable=False),
    sa.Column('dest_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('departure_gate', sa.String(), nullable=True),
    sa.Column('arrival_gate', sa.String(), nullable=True),
    sa.Column('departure_terminal', sa.String(), nullable=True),
    sa.Column('arrival_terminal', sa.String(), nullable=True),
    sa.Column('baggage_belt', sa.String(), nullable=True),
    sa.Column('checkin_counter', sa.String(), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_status_records_created_at'), 'flight_status_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_flight_status_records_dest_code'), 'flight_status_records', ['dest_code'], unique=False)
    op.create_index(op.f('ix_flight_status_records_flight_number'), 'flight_status_records', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flight_status_records_origin_code'), 'flight_status_records', ['origin_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_status_records_origin_code'), table_name='flight_status_records')
    op.drop_index(op.f('ix_flight_status_records_flight_number'), table_name='flight_status_records')
    op.drop_index(op.f('ix_flight_status_records_dest_code'), table_name='flight_status_records')
    op.drop_index(op.f('ix_flight_status_records_created_at'), table_name='flight_status_records')
    op.drop_table('flight_status_records')
    # ### end Alembic commands ###
